### ISSUE TITLE
the cpp files how to build so

### ISSUE THREAD

**Issue by huangtao-ola** [cocos/google-game-sdk#4]
in my flutter project,i do not want to use activity ,i want to change the activity to a flutter view.but in 3.6.2 version,the gameactivity instead of ,some native codes in game activity ,how to build the so file

**Comment by bofeng-song** [comment]
You can find this path in the engine editor installation directory resources\3d\engine\native\external\sources\android-gamesdk.

The compilation of the source code is determined by this file resources\3d\engine\native\external\sources\CMakeLists.txt, please modify it as necessary.

**Comment by huangtao-ola** [comment]
do you have a demo for building the game activity cpp to so file?

**Comment by bofeng-song** [comment]
All the code of the current engine is compiled into a single so, without separate compilation for game activity.

**Comment by huangtao-ola** [comment]
you mean ：i builded the ”libcocos.so“，has the game activity cpp codes?

**Comment by bofeng-song** [comment]
right
