### ISSUE TITLE
大佬，请教一个问题

### ISSUE THREAD

**Issue by huangtao-ola** [cocos/google-game-sdk#5]
现在cpp对应的Java方法是gameactivity_xxx ，如果我要编译成 TestActivity_xxx，这个时候要怎么搞，求大佬指点迷津

**Comment by bofeng-song** [comment]
1. GameActivity 是否存在，有的话TestActivity继承CocosActivity , 然后把你的逻辑放到TestActivity, 之后可以有个类似TestActivity.cpp添加对应的 JNI 接口
2. TestActivity_xxx 这个是干嘛用的，若存在继承关系，用Activity的对象可以调用到 TestActivity的接口，可以参考JniHelper里面接口的调用，看其他源码的实现
