### ISSUE TITLE
GameActivity不支持Lifecycle & ViewModel

### ISSUE THREAD

**Issue by Yetland** [cocos/google-game-sdk#7]
GameActivity 继承 Activity，无法使用Lifecycle

**Comment by bofeng-song** [comment]
可以自己更改继承关系，通过readMe重新打包jar

**Comment by Yetland** [comment]
> 

这个库和Google的game sdk有什么区别吗？

**Comment by bofeng-song** [comment]
这个只集成了引擎有用到的部分功能；可以clone这个仓库，改成继承CompatActivity，然后编译jar。将编译后的jar拷贝到指定目录，具体参考文档ReadMe

**Comment by Yetland** [comment]
> 这个只集成了引擎有用到的部分功能；可以clone这个仓库，改成继承CompatActivity，然后编译jar。将编译后的jar拷贝到指定目录，具体参考文档ReadMe

remove appcompat dependency & Repair that some switch buttons on the android platform do not respond
34d6f45c bofeng <bofeng.song@chukong-inc.com> on 2022/12/21 at 16:00

这次提交是把appcompact这个库移除了，然后使用了Activity。我试过把Activity替换成AppCompactActivity，但是编译出来的jar替换原有的会崩溃。

`runtime.cc:655]   native: #102 pc 0000000000003680  /system/bin/app_process64 (main+1592)
                                                           runtime.cc:655]   native: #103 pc 0000000000085190  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108)
                                                           runtime.cc:655]   at com.google.androidgamesdk.GameActivity.loadNativeCode(Native method)
                                                           runtime.cc:655]   at com.google.androidgamesdk.GameActivity.onCreate(GameActivity.java:266)
                                                           runtime.cc:655]   at com.cocos.lib.CocosActivity.onCreate(CocosActivity.java:65)`

**Comment by Yetland** [comment]
cocos creator 3.7.2自带的game-sdk.jar是在哪个提交上更改的？如果直接修改这个库下的最新代码会导致一些Native方法找不到

**Comment by bofeng-song** [comment]
> cocos creator 3.7.2自带的game-sdk.jar是在哪个提交上更改的？如果直接修改这个库下的最新代码会导致一些Native方法找不到

不包含这个修改：https://github.com/cocos/google-game-sdk/pull/6

后面我们再创建不同分支进行管理

**Comment by Yetland** [comment]
> > cocos creator 3.7.2自带的game-sdk.jar是在哪个提交上更改的？如果直接修改这个库下的最新代码会导致一些Native方法找不到
> 
> 不包含这个修改：#6
> 
> 后面我们再创建不同分支进行管理

那我需要回滚到哪个提交上做修改？

**Comment by bofeng-song** [comment]
revert https://github.com/cocos/google-game-sdk/pull/6 的修改，然后编译jar

**Comment by bofeng-song** [comment]
请使用3.7分支；我创建了3.7分支了
